apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: cluster-ca
  secretName: cluster-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 87600h # 10y
  renewBefore: 5m
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: cluster-ca-secret
