apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: net-narthollis-www

images:
- name: ghcr.io/narthollis/net_narthollis_www
  newTag: main@sha256:b9647103ab95f16f1f6229bf3c053e7e4314a3a5776db3dddcff12f84680c210

resources:
- resources/gateway.yaml
- resources/public.certificate.yaml
- resources/letsencrypt.issuer.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/httproute.yaml
