apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: net-narthollis-www

images:
- name: ghcr.io/narthollis/net_narthollis_www
  newTag: main@sha256:2f978e03dfbd714ef97a3140e20a0100117b4f40daf6a2a5d68a73f88e97f8d2

resources:
- resources/gateway.yaml
- resources/public.certificate.yaml
- resources/letsencrypt.issuer.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/httproute.yaml
