apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  namespace: media
  labels:
    app.kubernetes.io/name: downloaders
    app.kubernetes.io/component: filebrowser
    app.kubernetes.io/part-of: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: fast-block
