apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - resources/anonymous-oidc.crb.yaml
  - resources/kubernetes.backendtlsproxy.yaml
  - resources/oidc.certificate.yaml
  - resources/oidc.gateway.yaml
  - resources/oidc.httproute.yaml
  - resources/oidc.issuer.yaml

images:
  - name: nginx
    newTag: 1.29.2-alpine-slim

labels:
  - pairs:
      app.kubernetes.io/name: cluster-oidc-proxy
      app.kubernetes.io/version: 1.0.0
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - name: oidc-proxy-config
    files:
    - files/oidc-proxy.nginx.conf

# patches:
#   - target:
#       kind: Service
#       name: cilium-gateway-oidc
#     patch: |-
#       - op: remove
#         path: /spec/selector
