apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - resources/anonymous-oidc.crb.yaml
  - resources/oidc.gateway.yaml
  - resources/oidc.httproute.yaml
  - resoruces/kubernetes.backendtlsproxy.yaml
