apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: deluan/navidrome
  newTag: 0.63.2

resources:
- resources/gateway.yaml
- resources/public.certificate.yaml
- resources/letsencrypt.issuer.yaml
- resources/deployment.yaml
- resources/config.pvc.yaml
- resources/service.yaml
- resources/httproute.yaml
