apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/operator/default?ref=v0.34.0
- https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/operator/samples?ref=v0.34.0
patches:
- target:
    kind: Deployment
    name: intel-deviceplugins-controller-manager
  patch: |
    kind: Deployment
    metadata:
      name: intel-deviceplugins-controller-manager
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
            kubernetes.io/os: linux
