apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: oidc
spec:
  targetRefs:
    - group: core
      kind: Service
      name: kubernetes
      sectionName: https
  validation:
    hostname: kubernetes.default.svc.cluster.local
    caCertificateRefs:
      - group: core
        kind: ConfigMap
        name: kube-root-ca.crt
