apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: oidc
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http-gw
    hostname: oidc.moya.lemon.narthollis.net
  - protocol: HTTPS
    port: 443
    name: https-gw
    hostname: oidc.moya.lemon.narthollis.net
    tls:
      mode: Terminate
      certificateRefs:
        - group: ""
          kind: Secret
          name: oidc-moya-lemon-narthollis-net-tls
  infrastructure:
    labels:
      app.kubernetes.io/name: cluster-oidc-proxy
      app.kubernetes.io/version: 1.0.0
      bgp: blue
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-gateway-oidc
  namespace: kube-system
  labels:
    bgp: blue
spec:
  ipFamilyPolicy: PreferDualStack
  type: LoadBalancer
