apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: oidc-letsencrypt
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: oidc-issuer
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: oicd
                namespace: oidc
                kind: Gateway
