apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: downloaders
    app.kubernetes.io/component: sabnzbd
    app.kubernetes.io/part-of: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: downloaders
      app.kubernetes.io/component: sabnzbd
      app.kubernetes.io/part-of: media
  template:
    metadata:
      labels:
        app.kubernetes.io/name: downloaders
        app.kubernetes.io/component: sabnzbd
        app.kubernetes.io/part-of: media
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - containerPort: 8080
          name: http
        startupProbe:
          httpGet:
            port: http
            path: /sabnzbd/login/
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            port: http
            path: /sabnzbd/login/
          periodSeconds: 60
        readinessProbe:
          httpGet:
            port: http
            path: /sabnzbd/login/
          periodSeconds: 60
        env:
        - name: PUID
          value: "1000"
        - name: PGUID
          value: "1000"
        - name: TZ
          value: Australia/Adelaide
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: false
        - name: media-library
          mountPath: media
          readOnly: false
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
          limits:
            memory: 512Mi
            cpu: 1
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      - name: media-library
        persistentVolumeClaim:
          claimName: media-library
