apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
- resources/config.pvc.yaml
- resources/service.yaml
- resources/httproute.yaml

images:
- name: ghcr.io/dictionarry-hub/profilarr
  newTag: v2.0.9
- name: ghcr.io/dictionarry-hub/profilarr-parser
  newTag: 2.1.0
