cilium:
  fullnameOverride: cilium

  enable-ipv4: true
  enable-ipv6: true
  enable-ipv4-masquerade: true
  enable-ipv6-masquerade: true

  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 7445

  gatewayAPI:
    enabled: true

  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup

  ipam:
    mode: kubernetes

  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

  hubble:
    tls:
      auto:
        method: cronJob
