cilium:
  fullnameOverride: cilium

  ipv4:
    enabled: true

  ipv6:
    enabled: true

  enableIPv4Masquerade: true
  enableIPv6Masquerade: true

  k8s:
    requireIPv4PodCIDR: true
    requireIPv6PodCIDR: true

  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 7445

  gatewayAPI:
    enabled: true

  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup

  ipam:
    mode: kubernetes

  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

  hubble:
    tls:
      auto:
        method: cronJob
