apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.18.0
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.34.0

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: privileged