plex-media-server:
  image:
    # -- The public dockerhub registry
    repository: plexinc/pms-docker
    tag: "1.43.3.10896-cb3ebc72d"
  pms:
    storageClassName: fast-block
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
        gpu.intel.com/i915: 1

  extraEnv:
    HOSTNAME: "moya"
    TZ: "Australia/Adelaide"

  extraVolumeMounts:
  - name: media-library
    mountPath: /media-library/
  - name: tls
    mountPath: /run/secrets/tls/

  extraVolumes:
  - name: media-library
    persistentVolumeClaim:
      claimName: media-library
  - name: tls
    secret:
      secretName: plex-moya-lemon-narthollis-net-tls
