apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-moya-lemon-narthollis-net-tls
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: plex-letsencrypt
  dnsNames:
  - plex.moya.lemon.narthollis.net
  secretName: plex-moya-lemon-narthollis-net-tls
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: plex-moya-lemon-narthollis-net-tls-keystore
        key: password
      profile: Modern2023
      