# yaml-language-server: $schema=values.schema.json
traefik:
  ports:
    websecure:
      http3:
        enabled: true

  providers:
    kubernetesCRD:
      enabled: false
    kubernetesGateway:
      enabled: true
      experimentalChannel: true
    kubernetesIngress:
      enabled: false

  service:
    labels:
      bgp: blue
    spec:
      ipFamilyPolicy: RequireDualStack
