# yaml-language-server: $schema=values.schema.json
traefik:
  image:
    tag: v3.3.0-rc1

  ports:
    websecure:
      http3:
        enabled: true

  providers:
    kubernetesCRD:
      enabled: true
    kubernetesGateway:
      enabled: true
      experimentalChannel: true
    kubernetesIngress:
      enabled: false

  ingressRoute:
    dashboard:
      enabled: true

  gateway:
    enabled: false

  logs:
    general:
      level: INFO
    access:
      enabled: true

  service:
    labels:
      bgp: blue
    spec:
      ipFamilyPolicy: RequireDualStack
